version: "3.9"

services:
  db:
    image: postgres:16.2
    container_name: postgres_db
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      retries: 5
      timeout: 5s
    restart: on-failure

  external_simulator:
    build:
      context: .
      dockerfile: app/external_simulator/Dockerfile
    command: ["sh", "-c", "uvicorn app.external_simulator.main:app --host 0.0.0.0 --port 8001"]
    container_name: external_simulator
    ports:
      - "8001:8001"
    restart: unless-stopped

  query_service:
    build:
      context: .
      dockerfile: app/query_service/Dockerfile
    depends_on:
      db:
        condition: service_healthy
      external_simulator:
        condition: service_started
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    entrypoint: ["sh", "-c", "chmod +x app/query_service/entrypoint.sh && app/query_service/entrypoint.sh"]

  tests:
    build:
      context: .
      dockerfile: app/query_service/Dockerfile
    depends_on:
      db:
        condition: service_healthy
      external_simulator:
        condition: service_started
    command: [ "sh", "-c", "pytest" ]
    volumes:
      - ./:/app

volumes:
  pg_data:

